### ISSUE TITLE
Release new version with binary for Apple Silicon devices

### ISSUE THREAD

**Issue by der-eismann** [community-terraform-providers/terraform-provider-ignition#21]
Hi there,

one of our colleagues is working with a MacBook that uses an Apple Silicon CPU and it is always troublesome to compile the provider ourselves and google where you have to place the binary. It would be great if you could release a new version that includes a binary for the `darwin_arm64` platform!

**Comment by yussufsh** [comment]
Seems like we just need to create a new release without any code changes to support `darwin_arm64`?

**Comment by der-eismann** [comment]
I'm not 100% sure how goreleaser works, but at least `darwin` and `arm64` are already [in the matrix](https://github.com/community-terraform-providers/terraform-provider-ignition/blob/v2/.goreleaser.yml#L23-L28).

**Comment by yussufsh** [comment]
I am guessing last v2 release was before the platform support was added. Ref: https://github.com/goreleaser/goreleaser/releases/tag/v0.156.2

**Comment by yussufsh** [comment]
Re-opening as the release is failing because of older go version which does not support the given platform.

**Comment by yussufsh** [comment]
New version with darwin_arm64 is now available.
https://registry.terraform.io/providers/community-terraform-providers/ignition/latest

**Comment by der-eismann** [comment]
Awesome, thank you so much for your work!
Do you think you could do the same for the v1 branch? Or is it too old?
