### ISSUE TITLE
Convertion from octal to decimal not working for file/dir permissions

### ISSUE THREAD

**Issue by egeturgay** [community-terraform-providers/terraform-provider-ignition#4]
Hi there,

### Terraform Version
TF v12

### Affected Resource(s)
Please list the resources as a list, for example:
- directory permissions
- file permissions 

### Terraform Configuration Files
```hcl
data "ignition_directory" "java" {
    path = "/etc/java"
    mode = "0755"
}
```

### Expected Behavior
The Octal value should be converted to Decimal value for Ignition to work with as described by Hashicorp in https://github.com/hashicorp/terraform/issues/22143

### Actual Behavior
Octal value is passed as Decimal to Ignition which leads to incorrect permissions on files/directories.

### Important Factoids
This used to be converted correctly with the same ignition provider on TF v11, so I suspect HCL parser handled this in the earlier versions. This is however not the case with TF v12 and hashicorp expects this to be handled on the provider side.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
https://github.com/hashicorp/terraform/issues/22143

**Comment by egeturgay** [comment]
I don't think there is a viable way to implement this due to https://github.com/hashicorp/hcl2/issues/86 where HCL2 does not allow octal values in parsing. 
The octal values are converted to an integer removing the preceding 0 before they reach to the provider which makes determining whether the number is decimal or octal not possible.
IMHO, the support of octal mode should be removed from the documentation and users should use decimal values going forward.

**Comment by LorbusChris** [comment]
While this might be useful I don't think it's feasible to implement this.
I'm closing the issue.
