### ISSUE TITLE
Unsupported argument - append is not expected here

### ISSUE THREAD

**Issue by ironicbadger** [community-terraform-providers/terraform-provider-ignition#6]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

```
% terraform -v
Terraform v0.13.4

% terraform apply -v
Terraform v0.13.4
+ provider registry.terraform.io/community-terraform-providers/ignition v2.1.1
+ provider registry.terraform.io/hashicorp/vsphere v1.24.1
+ provider registry.terraform.io/terraform-providers/ignition v1.2.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `ignition_config`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
locals {
  ignition_encoded = "data:text/plain;charset=utf-8;base64,${base64encode(var.ignition)}"
}

data "ignition_config" "vm" {

  append {
    source = local.ignition_encoded
  }
  files = [
    data.ignition_file.hostname.rendered
  ]
}
```

It appears that Terraform never makes it inside the append block and fails because it's not expecting the append argument. This seems to be a regression over the upstream provider I think.

### Actual Behavior

The above code snippet works with the upstream provider. In an attempt to get ignition v3 files for RHCOS 4.6 generated I switched to the community provider. This results in the following error.

```
Error: Unsupported argument

  on ../../modules/rhcos-static/main.tf line 43, in data "ignition_config" "vm":
  43:   append = [

An argument named "append" is not expected here.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

Changes made to [this ocp4 repo](https://github.com/IronicBadger/ocp4/blob/4.5_static_ips/modules/rhcos-static/main.tf) if you're curious to get more context.

**Comment by bgilbert** [comment]
Ignition spec 3.x doesn't provide the `append` directive anymore; use `merge` instead.  For details on the difference between `append` and `merge`, see [here](https://coreos.github.io/ignition/operator-notes/#config-merging).
