### ISSUE TITLE
Error: Invalid data source "ignition_networkd_unit"

### ISSUE THREAD

**Issue by nacho-osete** [community-terraform-providers/terraform-provider-ignition#9]
### Terraform Version
Terraform v0.14.5
community-terraform-providers/ignition v2.1.1

### Affected Resource(s)
- The networkd_unit data source is missing

### Terraform Configuration Files
```hcl
Here's the related config snippet:

// example_virtual_machine_network_unit defines the systemd network units for
// each virtual machine.
data "ignition_networkd_unit" "example_virtual_machine_network_unit" {
  count   = length(var.esxi_hosts)
  name    = "00-ens192.network"
  content = data.template_file.example_virtual_machine_network_content.*.rendered[count.index]
}

[Full config set available there](https://github.com/hashicorp/terraform-provider-vsphere/tree/master/examples/ovf-template).
```

### Debug Output
https://gist.github.com/nacho-osete/66478d585fa0908992f5f195b6492100

### Expected Behavior
The networkd_unit data source should have worked out of the box, as expected.

### Actual Behavior
The data source is not available at the current provider anymore.

### Steps to Reproduce
terraform init; terraform plan

### Important Factoids
Config, scripts and toolset based on an older, working ovf-example for the [terraform-vsphere-provider](https://github.com/hashicorp/terraform-provider-vsphere/). I noticed that the current terraform ignition provider has some missing files at the moment; here's the related files (still present at the older, official hashicorp provider):

- https://github.com/hashicorp/terraform-provider-ignition/blob/master/ignition/resource_ignition_networkd_unit.go
- https://github.com/hashicorp/terraform-provider-ignition/blob/master/ignition/resource_ignition_networkd_unit_test.go

### References
- No related issues/pull requests yet (to be updated in the following week)

**Comment by bgilbert** [comment]
The provider in this repository only supports Ignition spec 3.x, which no longer has the `networkd` section.  If you're using Flatcar Container Linux and looking for a provider that supports Ignition spec 2.x, see [hashicorp/terraform-provider-ignition](https://github.com/hashicorp/terraform-provider-ignition).

**Comment by nacho-osete** [comment]
Thanks @bgilbert for quickly checking out the issue. 

Besides, just out of curiosity I wonder why the networkd section may have been removed in the spec 3.x: is there any workaround with the latest spec? Any quick/brief suggestion would be greatly appreciated (+1!)

**Comment by bgilbert** [comment]
It turns out that the `networkd` section wasn't doing anything special; it was just writing files.  You can use the `storage.files` section to write the config files directly to the correct paths.

**Comment by nacho-osete** [comment]
Thanks Benjamin for your patience and the insight, I will use the storage.files section for that :-)
